// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOKtqDxc5fQbrZFty8H2DIzADbhw7HYg',
    appId: '1:737796208771:web:3bbc69d68ebbbae54443b6',
    messagingSenderId: '737796208771',
    projectId: 'quickwork-52afd',
    authDomain: 'quickwork-52afd.firebaseapp.com',
    storageBucket: 'quickwork-52afd.firebasestorage.app',
    measurementId: 'G-084SVN8TXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXu4Aq4PAII8uKti7Nhq4BzBzRCIZoNE',
    appId: '1:737796208771:android:503f892ee86d3a954443b6',
    messagingSenderId: '737796208771',
    projectId: 'quickwork-52afd',
    storageBucket: 'quickwork-52afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBarNMvBiuO-LXisJJ6RYFWVaqSyp6sM',
    appId: '1:737796208771:ios:5bc97eac45319b3d4443b6',
    messagingSenderId: '737796208771',
    projectId: 'quickwork-52afd',
    storageBucket: 'quickwork-52afd.firebasestorage.app',
    iosBundleId: 'com.quickWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhBarNMvBiuO-LXisJJ6RYFWVaqSyp6sM',
    appId: '1:737796208771:ios:5bc97eac45319b3d4443b6',
    messagingSenderId: '737796208771',
    projectId: 'quickwork-52afd',
    storageBucket: 'quickwork-52afd.firebasestorage.app',
    iosBundleId: 'com.quickWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrOKtqDxc5fQbrZFty8H2DIzADbhw7HYg',
    appId: '1:737796208771:web:c235e4a7da2904764443b6',
    messagingSenderId: '737796208771',
    projectId: 'quickwork-52afd',
    authDomain: 'quickwork-52afd.firebaseapp.com',
    storageBucket: 'quickwork-52afd.firebasestorage.app',
    measurementId: 'G-NK21YGHR02',
  );
}
